version: '3.3'
#name: reddit_project
services:
  post_db:
    env_file:
    - .env
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back-net
  ui:
    env_file:
    - .env
    build: ./ui
    image: ${username}/ui:1.0
    ports:
      - 9292:9292/tcp
    networks:
      - front-net
  post:
    env_file:
      - .env
    build: ./post-py
    image: ${username}/post:1.0
    networks:
      - back-net
      - front-net
  comment:
    env_file:
    - .env
    build: ./comment
    image: ${username}/comment:1.0
    networks:
      - back-net
      - front-net

volumes:
  post_db:

networks:
  front-net:
  back-net:
